### PR TITLE
Add karma-spec-reporter

### PR DESCRIPTION
**Pull request by simplesthing**
Small change to add the karma-spec-reporter in order to see the tests as they execute.

### CODE REVIEW

**Comment by jvandemo** [comment]
@simplesthing Thanks, will try it out tomorrow and merge if OK. Thanks for your contribution!

**Comment by jvandemo** [comment]
Merged, thanks for your contribution @simplesthing. Much appreciated!

**Comment by jvandemo** [comment]
Released as v3.2.0. Change log has been updated and credits have been added. :+1:

**Comment by simplesthing** [comment]
Thanks for such a quick merge, and a great generator!

**Pull request merged**
