### PR TITLE
pass angular as parameter in main module (smaller minified output file)

### PR DESCRIPTION
**Pull request by theborakompanioni**

### CODE REVIEW

**Comment by jvandemo** [comment]
By smaller minified output I assume you mean the minifier will be able to replace the `angular` string occurrences with smaller variable names?

Thanks for the PR!

**Comment by theborakompanioni** [comment]
That's exactly what I mean - yes.

**Comment by jvandemo** [comment]
Thanks @theborakompanioni, great work again!

**Comment by theborakompanioni** [comment]
Great work? Not even noteworthy. You sir, are awesome. Thank you for your great generator!

**Comment by jvandemo** [comment]
Thank you @theborakompanioni, humbled by your great compliment. Much appreciated!

**Pull request merged**
